# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=4.2
group=com.mars.serversidehorror
java_version=21
deimos_version=2.7
# Common
mod_name=Server-Side Horror
mod_author=Mars
mod_id=serversidehorror
license=MIT
homepage=https://www.curseforge.com/minecraft/mc-mods/sever-side-horror
description=Fully Configurable Ambient Horror Mod
minecraft_version=1.21.11
minecraft_version_range=[1.21.11, 1.22)
neo_form_version=1.21.11-20251209.172050
parchment_minecraft=1.21.10
parchment_version=2025.10.12
# Fabric
fabric_version=0.141.1+1.21.11
fabric_loader_version=0.18.4
modmenu_version=17.0.0-beta.2
# Forge
forge_version=61.0.7
forge_loader_version_range=[61,)
# NeoForge
neoforge_version=21.11.37-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
